server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: notice-service
          uri: lb://NOTICE-SERVICE
          predicates:
            - Path=/api/notice/**


#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info, metrics, prometheus, gateway