spring:
  #  datasource:
  #    url: ${databaseUrl}
  #    driver-class-name: org.mariadb.jdbc.Driver
  #    username: ${databaseUserName}
  #    password: ${databasePassword}
  datasource:
    url: jdbc:h2:file:./mapshot-executor/maindb;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: ${databaseUserName}
    password: ${databasePassword}

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

lambda:
  host: ${lambdaHost}
  path: ${lambdaPath}

slack:
  url: ${slackUrl}

jwt:
  admin:
    secret: ${jwtAdminSecret}
    header: ADMIN_AUTH_TOKEN
    second: 3600

  image:
    secret: ${jwtImageSecret}
    header: AUTH_TOKEN
    second: 60
