spring:
  datasource:
    url: jdbc:h2:file:./mapshot-executor/maindb
    driverClassName: org.h2.Driver
    username: ${databaseUserName}
    password: ${databasePassword}

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  error:
    whitelabel:
      enabled: false

client:
  lambda:
    host: ${lambdaHost}
    timeout: ${lambdaTimeout}

  slack:
    url: ${slackUrl}

  naver:
    host: ${naverHost}
    path: ${naverPath}
    id: ${naverClientId}
    secret: ${naverClientSecret}

jwt:
  admin:
    secret: ${jwtAdminSecret}
    header: ADMIN_AUTH_TOKEN
    second: 3600

  image:
    secret: ${jwtImageSecret}
    header: AUTH_TOKEN
    second: 60

community:
  post:
    page_size: 10
  comment:
    page_size: 20

notice:
  post:
    page_size: 10

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
