spring:
  datasource:
    url: jdbc:h2:file:./mapshot-executor/maindb
    driverClassName: org.h2.Driver
    username: ${databaseUserName}
    password: ${databasePassword}

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

lambda:
  host: ${lambdaHost}
  path: ${lambdaPath}

slack:
  url: ${slackUrl}

jwt:
  admin:
    secret: ${jwtAdminSecret}
    header: ADMIN_AUTH_TOKEN
    second: 3600

  image:
    secret: ${jwtImageSecret}
    header: AUTH_TOKEN
    second: 60

community:
  post:
    page_size: 10

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
