url: jdbc:sqlite:./mapshot-executor/maindb.sqlite
driverClassName: org.sqlite.JDBC

spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
    encoding: UTF-8
    check-template-location: true

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  error:
    whitelabel:
      enabled: false

client:
  slack:
    url: ${slackUrl}

  naver:
    url: ${naverUrl}
    id: ${naverClientId}
    secret: ${naverClientSecret}

  gov:
    url: ${govUrl}

jwt:
  admin:
    secret: ${jwtAdminSecret}
    header: ADMIN_AUTH_TOKEN
    second: 3600


community:
  post:
    page_size: 10
  comment:
    page_size: 20

notice:
  post:
    page_size: 10

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: app
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'

sentry:
  dsn: https://04217465cb42cf9e796efc0b8311463b@o4505030048284672.ingest.us.sentry.io/4508625584390144
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for tracing.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0


bucket:
  tokenCount: 60