spring:
  datasource:
    url: ${databaseUrl}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${databaseUserName}
    password: ${databasePassword}

  jpa:
    hibernate:
      ddl-auto: none

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

lambda:
  host: ${lambdaHost}
  path: ${lambdaPath}

slack:
  url: ${slackUrl}