spring:
  datasource:
    url: ${databaseUrl}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${databaseUserName}
    password: ${databasePassword}

  jpa:
    #    properties:
    #      hibernate:
    #        format_sql: true
    hibernate:
      ddl-auto: none
