receivers:
  otlp:
    protocols:
      grpc: # on port 4317
      http: # on port 4318
  prometheus:
    config:
      scrape_configs:
        - job_name: "app-mapshot"
          scrape_interval: 5s
          metrics_path: "/actuator/prometheus"
          static_configs:
            - targets:
                - "app-mapshot:8081"

  fluentforward:
    endpoint: 0.0.0.0:8006

processors:
  batch:
  resource:
    attributes:
      - action: insert
        key: service_name
        from_attribute: service.name
      - action: insert
        key: service_namespace
        from_attribute: service.namespace
      - action: insert
        key: compose_service
        from_attribute: compose_service
      - action: insert
        key: loki.resource.labels
        value: service_name, service_namespace, compose_service



exporters:
  logging:
    loglevel: debug
  # metrics
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
  # traces
  otlp/tempo:
    endpoint: http://tempo:4317
    tls:
      insecure: true
      insecure_skip_verify: true
  # logs
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [ health_check, pprof, zpages ]
  pipelines:
    metrics:
      receivers: [ prometheus ]
      processors: [ batch ]
      exporters: [ prometheusremotewrite ]
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp/tempo ]
    logs:
      receivers: [ otlp ]
      processors: [ resource ]
      exporters: [ loki ]
