name: build-prod

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev
      - feature/*

jobs:
  build:
    name: build-prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Jib
        env:
          REPO_PATH: ${{ secrets.MAPSHOT_DOCKERHUB_REPO_PATH }}
        run: ./gradlew jib -x test
          -Djib.to.image=$REPO_PATH
          -Djib.to.tags=mapshot-prod
          -Djib.container.creationTime=USE_CURRENT_TIMESTAMP
          -Djib.container.jvmFlags=-XX:MaxRAMPercentage=30.0,-XX:MinRAMPercentage=30.0,-Duser.timezone=Asia/Seoul
