name: deploy-prod

on:
  workflow_dispatch:

jobs:
  depoly:
    name: deploy-prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_SSH_HOST }}
          username: ${{ secrets.OCI_SSH_USERNAME }}
          key: ${{ secrets.OCI_SSH_KEY }}
          passphrase: ${{ secrets.OCI_SSH_PASSPHRASE }}
          script: |
            cd /home/${{ secrets.OCI_SSH_USERNAME }}/
            docker-compose down --rmi all
            docker-compose up -d
