name: deploy-dev

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - 'README.md'

jobs:
  depoly:
    name: CI/CD release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Native Image
        run: ./gradlew bootBuildImage

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #      - name: Mapshot Jib
      #        env:
      #          MAPSHOT_EXECUTOR_DOCKERHUB_REPO_PATH: ${{ secrets.MAPSHOT_DOCKERHUB_REPO_PATH }} # dev 따로 운영해야하나?
      #        run: ./gradlew jib -x test
      #          -Djib.to.image=$MAPSHOT_EXECUTOR_DOCKERHUB_REPO_PATH
      #          -Djib.to.tags=mapshot-executor

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_SSH_HOST }}
          username: ${{ secrets.OCI_SSH_USERNAME }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            cd /home/${{ secrets.OCI_SSH_USERNAME }}/
            docker-compose down --rmi all
            docker-compose up -d
